# Generated by Django 5.2.11 on 2026-04-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyurtma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mijoz_nomi", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=20)),
                ("mahsulot_nomi", models.CharField(max_length=255)),
                ("narxi", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sana", models.DateTimeField(auto_now_add=True)),
                ("holat", models.CharField(default="Kutilmoqda", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Mahsulot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
                ("narxi", models.DecimalField(decimal_places=2, max_digits=10)),
                ("miqdori", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mijoz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism", models.CharField(max_length=50)),
                ("tel", models.CharField(max_length=20)),
            ],
        ),
    ]
