# Generated by Django 4.2.30 on 2026-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikkinchi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahsulot",
            name="birligi",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
