# Generated by Django 4.2.30 on 2026-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikkinchi", "0002_mahsulot_birligi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mijoz",
            name="tel",
        ),
        migrations.AddField(
            model_name="mijoz",
            name="manzil",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mijoz",
            name="telefon",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mijoz",
            name="ism",
            field=models.CharField(max_length=100),
        ),
    ]
