# Generated by Django 4.2.30 on 2026-04-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikkinchi", "0003_remove_mijoz_tel_mijoz_manzil_mijoz_telefon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mahsulot",
            name="birligi",
        ),
        migrations.AlterField(
            model_name="mahsulot",
            name="miqdori",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
